version: '3'

services:
    mongo:
        hostname: mongo
        container_name: mongo
        image: mongo
        ports:
            - 27017:27017
        restart: always
       # volumes:
           # - ./data:/data/db
    api: 
        build: .
        ports: 
            - "8080:8080"
        depends_on: 
            - mongo